### ISSUE TITLE
missing validators.js in src/components/

### ISSUE THREAD

**Issue by akocmark** [srlopez/rntest#2]
Inside src/components/FTextInput.js

this line is requiring a missing file. `import * as validators from './validators';`

where can I get this file from?

Thanks

**Comment by akocmark** [comment]
this file is also missing `import FSubmitButton from '../components/FSubmitButton'`

**Comment by srlopez** [comment]
Already there!
Sorry

**Comment by srlopez** [comment]
then run with
./nurse -i "iPhone 6s Plus" -p App -b "org.reactjs.native.example"

**Comment by akocmark** [comment]
got it
thanks for quick response!

closing this now
